const movies = [
  {
    id: 1,
    title: 'Koe no katachi',
    ptTitle: 'A Voz do Silêncio',
    storyline: "Um jovem é excluído por seus colegas depois de intimidar uma menina surda ao ponto de mudar de escola. Anos depois, ele parte para o caminho da redenção.",
    rating: 4.1,
    imagePath: 'images/aSilentVoice.jpg',
    bookmarked: true,
    director: 'Naoko Yamada',
    genre: 'Drama',
  },
  {
    id: 2,
    title: 'A Quiet Place',
    ptTitle: 'Um Lugar Silencioso',
    storyline: "Em um mundo pós-apocalíptico, uma família é forçada a viver em silêncio enquanto se esconde de monstros com audição ultra-sensível.",
    rating: 3.8,
    imagePath: 'images/aQuietPlace.jpg',
    bookmarked: true,
    director: 'John Krasinski',
    genre: 'Terror',
  },
  {
    id: 3,
    title: 'The Dark Knight',
    ptTitle: 'Batman: O Cavaleiro das Trevas',
    storyline: "Quando a ameaça conhecida como O Coringa surge de seu passado, causa estragos e caos nas pessoas de Gotham. O Cavaleiro das Trevas deve aceitar um dos maiores testes para combater a injustiça.",
    rating: 4.5,
    imagePath: 'images/batman.jpeg',
    bookmarked: true,
    director: 'Christopher Nolan',
    genre: 'Ação',
  },
  {
    id: 4,
    title: 'Inception',
    ptTitle: 'A Origem',
    storyline: "Um ladrão que rouba segredos corporativos através do uso de tecnologia é dado a tarefa inversa de plantar uma idéia na mente de um C.E.O.",
    rating: 4.4,
    imagePath: 'images/inception.jpg',
    bookmarked: true,
    director: 'Christopher Nolan',
    genre: 'Ação',
  },
  {
    id: 5,
    title: 'Interstellar',
    ptTitle: 'Interestelar',
    storyline: "Uma equipe de exploradores viaja através de um buraco de minhoca no espaço, na tentativa de garantir a sobrevivência da humanidade.",
    rating: 4.3,
    imagePath: 'images/interstellar.jpg',
    bookmarked: true,
    director: 'Christopher Nolan',
    genre: 'Sci-Fi',
  },
  {
    id: 6,
    title: 'Kimetsu no Yaiba: Mugen Ressha-Hen',
    ptTitle: 'Demon Slayer - Mugen Train',
    storyline: "Tanjiro Kamado, junto com Inosuke Hashibira e Zenitsu Agatsuma embarcam no Trem do Infinito em uma nova missão com o Pilar de Fogo, Kyojuro Rengoku, para derrotar um demônio que tem atormentado as pessoas.",
    rating: 4.2,
    imagePath: 'images/kimetsu.png',
    bookmarked: true,
    director: 'Haruo Sotozaki',
    genre: 'Ação',
  },
  {
    id: 7,
    title: 'Lo imposible',
    ptTitle: 'O Impossível',
    storyline: "A história de uma família de turistas na Tailândia presa na destruição e subsequente caos do tsunami de 2004.",
    rating: 3.8,
    imagePath: 'images/oImpossivel.jpeg',
    bookmarked: true,
    director: 'J.A. Bayona',
    genre: 'Drama',
  },
  {
    id: 8,
    title: 'What Happened to Monday',
    ptTitle: 'Onde Está Segunda?',
    storyline: "Em um mundo onde as famílias são limitadas a um filho devido à superpopulação, um conjunto de septupletos idênticos deve evitar ser adormecido pelo governo enquanto investigam o desaparecimento de um deles.",
    rating: 3.5,
    imagePath: 'images/segunda.jpg',
    bookmarked: true,
    director: 'Tommy Wirkola',
    genre: 'Max Botkin',
  },
  {
    id: 9,
    title: 'Original title: Spider-Man: Homecoming',
    ptTitle: 'Homem-Aranha: De Volta ao Lar',
    storyline: "Peter Parker equilibra a sua vida como um estudante normal com o seu super herói, o Homem Aranha, mas encontrará um rastro de uma nova ameaça que ronda os céus da cidade de Nova York.",
    rating: 3.7,
    imagePath: 'images/spiderMan.jpg',
    bookmarked: true,
    director: 'Jon Watts',
    genre: 'Ação',
  },
  {
    id: 10,
    title: 'Tenet',
    ptTitle: 'Tenet',
    storyline: "Armado com apenas uma palavra, Tenet, e lutando pela sobrevivência do mundo inteiro, um Protagonista viaja por um mundo crepuscular de espionagem internacional em uma missão que se desdobrará em algo além do tempo real.",
    rating: 3.7,
    imagePath: 'images/tenet.jpeg',
    bookmarked: true,
    director: 'Christopher Nolan',
    genre: 'Ação',
  },
  // {
  //   id: ,
  //   title: '',
  //   ptTitle: '',
  //   storyline: "",
  //   rating: ,
  //   imagePath: 'images/.jpg',
  //   bookmarked: true,
  //   director: '',
  //   genre: '',
  // },
];

export default movies;
